language: python

env:
 global:
  - DEPENDS="numpy"
  - FCOMPILER="gnu95"
  - PREFIX="/tmp/pytdlpack"

python:
  - "3.6"
  - "3.7"
  - "3.8"

addons:
 apt:
  packages:
   - gfortran

before_install:
 - pip install $DEPENDS

install:
 - python setup.py build_ext --fcompiler=$FCOMPILER build
 - python setup.py install --prefix=$PREFIX

script:
 - python setup.py test
