#language: python
language: c

sudo: required

before_install:
  - sudo apt-get install gfortran

env:
  global:
    - DEPENDS="numpy"
    - FCOMPILER="gnu95"
    - PREFIX="/tmp/pytdlpack"

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

notifications:
  email: true

before_install:
  - pip install $DEPENDS

install:
  - python setup.py build_ext --fcompiler=$FCOMPILER build
  - python setup.py test
  - python setup.py install --prefix=$PREFIX